version: '2'
services:
  mongo-config1:
    image: mongo
    container_name: mongo-config1
    command: [mongod, --configsvr, --replSet, my-mongo-set, --dbpath, /data/db]
    ports:
      - "27019"
    networks:
      -  mongo-net
    volumes:
      - config-data1:/data
  mongo-config2:
    image: mongo
    container_name: mongo-config2
    command: [mongod, --configsvr, --replSet, my-mongo-set, --dbpath, /data/db]
    ports:
      - "27019"
    networks:
      -  mongo-net
    volumes:
      - config-data2:/data
  mongo-config3:
    image: mongo
    container_name: mongo-config3
    command: [mongod, --configsvr, --replSet, my-mongo-set, --dbpath, /data/db]
    ports:
      - "27019"
    networks:
      -  mongo-net
    volumes:
      - config-data3:/data
  mongo-shard1:
    image: mongo
    container_name: mongo-shard1
    command: [mongod, --shardsvr, --replSet, my-mongo-set]
    networks:
      -  mongo-net
    volumes:
      - shard-data1:/data
  mongo-shard2:
    image: mongo
    container_name: mongo-shard2
    command: [mongod, --shardsvr, --replSet, my-mongo-set]
    networks:
      -  mongo-net
    volumes:
      - shard-data2:/data
  mongo-shard3:
    image: mongo
    container_name: mongo-shard3
    command: [mongod, --shardsvr, --replSet, my-mongo-set]
    networks:
      -  mongo-net
    volumes:
      - shard-data3:/data
  mongo-query:
    image: mongo
    restart: unless-stopped
    links:
      - mongo-config1
      - mongo-config2
      - mongo-config3
      - mongo-shard1
      - mongo-shard2
      - mongo-shard3
    ports:
      - 27017:27017
    container_name: mongo-query
    command: [mongos, --configdb, "my-mongo-set/mongo-config1:27019,mongo-config2:27019,mongo-config3:27019"]
    networks:
      -  mongo-net
    volumes:
      - query-data:/data
  mongo-init:
    image: clarkzjw/mongo-init
    container_name: init
    links:
      - mongo-query
    environment:
      - DBNAME={{ DBNAME }}
    networks:
      -  mongo-net

networks:
    mongo-net:
        driver: bridge
        
volumes:
  config-data1: {}
  config-data2: {}
  config-data3: {}
  shard-data1: {}
  shard-data2: {}
  shard-data3: {}
  query-data: {}