version: '2'
services:
  mongo-config1:
    image: mongo
    container_name: mongo-config1
    command: [mongod, --configsvr, --replSet, my-mongo-set, --dbpath, /data/db]
    ports:
      - "27019"
    networks:
      -  mongo-net
  mongo-config2:
    image: mongo
    container_name: mongo-config2
    command: [mongod, --configsvr, --replSet, my-mongo-set, --dbpath, /data/db]
    ports:
      - "27019"
    networks:
      -  mongo-net
  mongo-config3:
    image: mongo
    container_name: mongo-config3
    command: [mongod, --configsvr, --replSet, my-mongo-set, --dbpath, /data/db]
    ports:
      - "27019"
    networks:
      -  mongo-net
  mongo-init1:
    image: clarkzjw/mongo-init1
    container_name: init1
    links:
      - mongo-config1
      - mongo-config2
      - mongo-config3
    networks:
      -  mongo-net
  mongo-shard1:
    image: mongo
    container_name: mongo-shard1
    command: [mongod, --shardsvr, --replSet, my-mongo-set]
    networks:
      -  mongo-net
  mongo-shard2:
    image: mongo
    container_name: mongo-shard2
    command: [mongod, --shardsvr, --replSet, my-mongo-set]
    networks:
      -  mongo-net
  mongo-shard3:
    image: mongo
    container_name: mongo-shard3
    command: [mongod, --shardsvr, --replSet, my-mongo-set]
    networks:
      -  mongo-net
  mongo-init2:
    image: clarkzjw/mongo-init2
    container_name: init2
    links:
      - mongo-shard1
      - mongo-shard2
      - mongo-shard3
    networks:
      - mongo-net
  mongo-query:
    image: mongo
    restart: unless-stopped
    links:
      - mongo-init1
      - mongo-init2
    ports:
      - 27017:27017
    container_name: mongo-query
    command: [mongos, --configdb, "my-mongo-set/mongo-config1:27019,mongo-config2:27019,mongo-config3:27019"]
    networks:
      -  mongo-net
  mongo-init3:
    image: clarkzjw/mongo-init3
    container_name: init3
    links:
      - mongo-query
    networks:
      -  mongo-net

networks:
    mongo-net:
        driver: bridge
